-- 코드를 입력하세요
SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
from ONLINE_SALE
where SALES_DATE < '2022-04-01' AND SALES_DATE >= '2022-03-01'

UNION ALL

SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
from OFFLINE_SALE
where SALES_DATE < '2022-04-01' AND SALES_DATE >= '2022-03-01'

ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC
