-- 코드를 입력하세요
SELECT i.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.FAVORITES, i.ADDRESS, ROUND(AVG(r.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO i join REST_REVIEW r on i.rest_id = r.rest_id
where i.ADDRESS LIKE '서울%'
group by REST_ID
order by SCORE DESC, FAVORITES DESC;
