select ROUTE, 
    CONCAT(ROUND(sum(D_BETWEEN_DIST), 1), 'km') AS TOTAL_DISTANCE, 
    CONCAT(ROUND(AVG(D_BETWEEN_DIST), 2), 'km') AS AVERAGE_DISTANCE
from SUBWAY_DISTANCE
group by route
order by sum(D_BETWEEN_DIST) desc;