SELECT b.TITLE, b.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, r.CREATED_DATE
FROM USED_GOODS_BOARD b join USED_GOODS_REPLY r on b.BOARD_ID = r.BOARD_ID
WHERE B.CREATED_DATE >= '2022-10-01'
  AND B.CREATED_DATE <  '2022-11-01'
order by r.CREATED_DATE asc, b.TITLE asc;